### ISSUE TITLE
How to evaluate my custom build?

### ISSUE THREAD

**Issue by GYingchao** [NTIA/WEnets#6]
Hi,

I just clone the repo and made my build of the c++ version. Unfortunately the Pearson correlation happens to be -0.44 when I use it in my polqa dataset. I guess there should be something wrong with it, how can I make sure the build is as good as your expectation? Could you kindly provide some conformance data to help? I already saw some test wave files under speech folder, without any expected output.

Thanks,
Richard

**Comment by GYingchao** [comment]
![image](https://user-images.githubusercontent.com/3379389/93986140-88d9b400-fdb8-11ea-9dbe-7449e3943bcd.png)

**Comment by acatellierNTIA** [comment]
Hi @GYingchao , there are some expected output values for the Matlab version found in this file:

https://github.com/NTIA/WEnets/blob/master/matlab/demo.m

The C++ output won't match the numbers in that file exactly, but they will be close. FWIW, the POLQA scores for the `*_D401.wav` files are the three digits that follow `Q` divided by 100.

That said, I'm noticing that in your sample the WAWEnet outputs occupy a small range of the scale from ~4.2 to ~4.5, and the POLQA outputs span the range from ~3.5 to ~3.8. This is roughly only 7.5% of the scale in both cases. My guess is that with more samples that span more of the scale, the correlation will improve.
